# Generated by Django 6.0.5 on 2026-05-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_recipephoto_image_album_recipephoto_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='albums/'),
        ),
    ]
