# Generated by Django 6.0.5 on 2026-05-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recipephoto',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
